### ISSUE TITLE
Doesn't compile under Alexandria

### ISSUE THREAD

**Issue by EZeroDivide** [Pigrecos/TensorFlow.Delphi#1]
Delphi 11 Alexandria Update 2

1.
Many ProtoGen units not part of the project.

2.
class function TFTensor.TF_NewTensor(data: TArray<Byte>; shape: TFShape; dtype: TF_DataType):PTF_Tensor;
begin
     ...
     if Assigned(data)  then
       **Move(@data[0], ttensor^, _length);**  // should be data[0] instead of @data[0] ?
     ...
end;

**Comment by Pigrecos** [comment]
To compile you need some external libraries:
Spring4d : https://bitbucket.org/sglienke/spring4d/src/master/
LoggerPro : https://github.com/danieleteti/loggerpro
Neon : https://github.com/paolo-rossi/delphi-neon
IPWorks Zip : https://www.nsoftware.com/ipworks/zip/download.aspx

1 : They are included in the project because some of them will be needed in the future.
2 : yes you are right it is a mistake. Thank you very much

**Comment by syberi** [comment]
Delphi 10.4 Tensorflow.array_ops 321 error :  for var item in TUtils.zip<TNDArray,Integer>(ePaddings_constant, eInput_shape) do
[dcc32 Error] Tensorflow.array_ops.pas(321): E2250 There is no overloaded version of 'TUtils.zip<TensorFlow.DApi.TNDArray,_System.**Integer**_>' that can be called with these arguments

**Comment by Pigrecos** [comment]
@syberi  it's not the latest commit and the function is this:
`class function TUtils.zip<T1, T2>(e1 : Enumerable<T1>; e2 : TEnumerable<T2>): Enumerable<Tuple<T1,T2>> ;
begin
    var eE2 : Ienumerable<T2> := TCollections.CreateList<T2>(e2.ToArray) ;
    var r := e1.Zip<T2, Tuple<T1,T2> >( eE2,function(first:  T1; second : T2 ): Tuple<T1,T2>
                                                begin
                                                    Result := Tuple<T1,T2>.Create(first,second)
                                                end );
    Result := r;
end;`
check the code or show me an example
P.S. Enumerable<T1> is class of Spring4d.Collection.Enumerable

**Comment by syberi** [comment]
i did try  TensorFlowProject from this rep., and Enumerable is class of Spring.Collection.Enumerable , is not class of Spring4d.Collection.Enumerable, i cant find classes [Spring4d...(from](https://ibb.co/R9DP46C) here  https://bitbucket.org/sglienke/spring4d/src/master/) 
i don't understand what i'm doing wrong
unit Tensorflow.array_ops
```

` // Restore shape information where possible.
    if  not tf.Context.executing_eagerly then
    begin
        var paddings_constant := TUtils.constant_value(paddings);
        var input_shape := result.op.inputs[0].shape;

        var ePaddings_constant := Enumerable<TNDArray>.Create([paddings_constant]);
        var eInput_shape       := Spring.Collections.Lists.TList<Integer>.Create(input_shape.as_int_list); - **here If you do not explicitly specify the class , tries to take System.Generics.Collections.Lists and and causes an error**

        if (input_shape.ndim > -1) and (not result.shape.IsFullyDefined) and (not(paddings_constant = nil)) then
        begin
            var new_shape := TList<Integer>.Create;
            try
              {TODO -o Max-cGeneral : Zip function verify!!}
              for var item in TUtils.zip<TNDArray,Integer>(ePaddings_constant, eInput_shape) do - **Here is the error described above**
              begin
                  var padding := item.Value1;
                  var dim     := Item.Value2;
                  if (padding = nil) or (dim = -1) or (TArray.Contains<Integer>(padding.ToArray<Integer>, -1) ) then
                      new_shape.Add(-1)
                  else
                      new_shape.Add( NDarray(np.sum(padding)) + dim );
              end;
              result.shape := new_shape.ToArray;
            finally
              new_shape.free;
            end;
        end;
    end;`
```

**Comment by Pigrecos** [comment]
This not last committ, update last committ.

[` var ePaddings_constant := Enumerable<TNDArray>.Create([paddings_constant]);
  var eInput_shape           := TList<Integer>.Create(input_shape.as_int_list);`](https://github.com/Pigrecos/TensorFlow.Delphi/blob/da7ea6faeed84ce4f789b645a4757a1f376b382d/src/Operation/Tensorflow.array_ops.pas#L317)
