### ISSUE TITLE
Compile 10.4 Alexandria "tensorflow-cpu-win64-2.11.0.dll" not found

### ISSUE THREAD

**Issue by RAT-Daddy01** [Pigrecos/TensorFlow.Delphi#3]
At runtime for 10.4 Alexandria tensorflow-cpu-win64-2.11.0.dll was not found. 
I have 0 errors when compiling TensorFlow.Delphi for 10.4 Alexandria though.
I tried install via https://www.tensorflow.org/install/lang_c and input tensorflow.dll within the dir renaming it to tensorflow-cpu-win64-2.11.0.dll with little success may you also include this in the [External libraries]?

Appreciate you including delphi compatibilities.

**Comment by Pigrecos** [comment]
Download libTensorflow 2.11 from https://www.tensorflow.org/install/lang_c?hl=en and rename to 'tensorflow-cpu-win64-2.11.0.dll'
